### ISSUE TITLE
Feature request: Copy ordered/unordered lists from the webpage

### ISSUE THREAD

**Issue by indera** [chitsaou/copy-as-markdown#29]
Do you think it would be useful to allow copying a block of the webpage text to markdown?

**Comment by isikyus** [comment]
+1 to this -- it's something I often need when quoting text in tools like Trello, where you type as Markdown, but copying a previous comment gives you HTML (which loses all formatting when you paste it into the Markdown box).

**Comment by chitsaou** [comment]
I just replied a similar request (https://github.com/chitsaou/copy-as-markdown/issues/79#issuecomment-546562533), but Trello sounds like a useful use case.

I don't know how frequent people may copy paste between other website contents and Trello, but my current suggestion would be using tools such as [turndown](https://github.com/domchristie/turndown) that converts HTML to Markdown, or substitute them with editors that support multiple cursors such as VScode or Atom.

Anyway, the support to "convert web content to Markdown" would be very limited and the final result would vary due to the supported tags in target Markdown parser. For now I don't think it's something that I would spend my effort on it.
