### ISSUE TITLE
[Suggestion] Better Copy Link Text for Firefox

### ISSUE THREAD

**Issue by Quantum00** [chitsaou/copy-as-markdown#45]
Hey, I am trying to find an alternative to [CoLT](https://addons.mozilla.org/en-US/firefox/addon/colt/) since that seems abandoned and I have found you addon.
Would it be possible to implement identical functionality? Like copying just the link text and even better if it can be an option on the main right click. (for example with CoLT I can right click and select Copy Link Text right away or even faster right click and press "x" on the keyboard because the developer added that shortcut)
Thanks

**Comment by chitsaou** [comment]
It took me few minutes to understand what you are saying. I am a daily Chrome user, and in Chrome (and most Webkit-based browsers) when you right-click on a link, the link text itself will be highlighted, so I can simply choose "Copy" and paste into a text editor.

But for Firefox, it does not work like Chrome. When I right-click on a link, the text itself is not highlighted. I think that's why you need such feature. Please correct me if I am wrong.

Speaking of this feature, actually there are many feature requests about "customizable format". I will implement such feature so you can customize whatever format you want to copy :)

**Comment by Quantum00** [comment]
Thanks!!

**Comment by chitsaou** [comment]
Solved by #55
