### ISSUE TITLE
Extending Firefox functionality

### ISSUE THREAD

**Issue by EdvardasDlugauskas** [chitsaou/copy-as-markdown#46]
Hi,

I'd like to copy articles and automatically include links as markdown (italics, bolds, etc. would be nice as well). 

I can implement the logic myself, but could you point me in the right direction? Which files would I need to edit to create a button on right click, where do I need to put my logic and so on.

Thanks

**Comment by chitsaou** [comment]
Thanks for your suggestion. Unfortunately this add-on is not made for that purpose in the beginning, so I personally don't prefer this feature in CopyAsMarkdown. However it is possible to do so if you could find some html to markdown library.

For the question you asked, in order to add a right-click menu item, you'll need to edit https://github.com/chitsaou/copy-as-markdown/blob/master/src-fx/index.js , and to do conversion you'll need to edit https://github.com/chitsaou/copy-as-markdown/blob/master/src-fx/lib/copy-as-markdown.js . However, you might get some problem getting DOM / HTML from the API.

I'm working on a new WebExtension-based add-on #33 . It'll eventually be converted to Chrome-compatible version. The current Firefox add-on will be deprecated in favor of the cross-browser WebExtension. If I found this idea easy to implement in the new framework, I'll probably add it to thew new version.

**Comment by EdvardasDlugauskas** [comment]
Thanks

**Comment by chitsaou** [comment]
Hi,

Just want to let you know that I've released new version for Firefox 57.

If you visit [the addon page](https://addons.mozilla.org/en-US/firefox/addon/copy-as-markdown/) with Firefox 57, you should see it can be installed in Firefox.

I'll close this issue for now. Please try it and let me know if you get more issues.

Thanks!
