### ISSUE TITLE
Why does the newest version for Chrome require additional permissions?

### ISSUE THREAD

**Issue by kenny-evitt** [chitsaou/copy-as-markdown#50]
Thanks for this extension! It's fantastic.

I just discovered that Chrome has disabled the extension because it now requires additional permissions. I can't tell what permissions are new but Chrome states:

>  It can now:
>
>  - Read your browsing history
>  - Modify data you copy and paste

Which of the permissions is new? Why is the new permission needed? Why is the 'browsing history' permission needed?

I'm assuming the 'copy and paste' permission is just allowing the extension to change the contents of the clipboard/pasteboard – is that correct?

**Comment by chitsaou** [comment]
Thanks for the report.

This is weird to me because I released an unpublished beta version 2.0.0rc2 yesterday. Normal users should not be affected.

The "additional permissions" is unexpected to me, too, because when I compare the error message and the actual permission I am using, they don't match. The extension doesn't read your browser history, and it does not have permissions that will trigger copy & paste warning, according to the doc.

However, you should see "Access your browsing activity" which is for accessing all tabs in all windows. The extension only access tab title and URL, and write it to clipboard . It does not store or transfer browsing data to other place. Only Chrome and your OS clipboard.

For technical details of your question, according to this page: https://developer.chrome.com/extensions/permission_warnings

And the current permissions used: https://github.com/chitsaou/copy-as-markdown/blob/master/src/manifest.chrome.json

Just want to clear, is your current version 2.0.0rc2 ?

**Comment by kenny-evitt** [comment]
@chitsaou My current version is "2.0.0rc2".

I noticed these lines in the new Chrome manifest file:

```json
  "version": "2.0.0",
  "version_name": "2.0.0rc2",
  "manifest_version": 2,
```

The new Firefox manifest file doesn't have a `version_name` key but it's `version` was updated:

```json
  "version": "2.0.0rc2",
  "manifest_version": 2,
```

Maybe the permissions didn't change and I'm just being prompted to approve the same permissions – tho I shouldn't need to do that, right?

**Comment by chitsaou** [comment]
So Chrome Web Store shipped a version that supposed to be a draft. Good. I must misread something.

Unfortunately I can't revert to older version, which means I must fix it as soon as possible.

The reason that they have different version value is incompatibility of those platforms. Firefox allows "rc", "beta" in `version` to indicate it's a beta version (and they have a extremely nice version management tool), while Chrome does not allow anything other than semver in `version` attribute. That's why they're separate.

For the permissions, you should not be prompted to accept them. Though I think `clipboardWrite` is unnecessary for Chrome because it works without such permission. The weird thing is that the doc says `clipboardWrite` does not trigger permission warning, but in fact it triggers.

Please allow me to fix this in two days. In the meanwhile, it'd be great if you could try some features and let me know if something is broken.

Cheers!

**Comment by kenny-evitt** [comment]
@chitsaou No worries! I would be glad to help; I rely on this extension.

I imagine it might be related, but I just gave in and accepted the 'new' permissions. Now tho my previously setup keyboard shortcuts don't work and the only thing visible under "Options" is "Escape Markdown code".

**Comment by chitsaou** [comment]
The keyboard shortcut is another thing confusing me. In #49 it is reported that keyboard shortcuts is missing, but the settings is supposed to be saved in Chrome and being used in newer version. I might accidentally changed the key. I'll check it.

For keyboard shortcut settings, Chrome put them in `Keyboard shortcuts` page. You can find a link at the bottom of Extensions page. This is the only place that you can set a keyboard shortcut for an extension. But I think it's good to put a short guide about how to set keyboard shortcuts in options page.

**Comment by kenny-evitt** [comment]
@chitsaou Actually, none of the options under the popup menu work either; I can't copy any links.

**Comment by kenny-evitt** [comment]
@chitsaou You're right about the location of the keyboard shortcut settings; my bad for forgetting. I checked and the previous shortcut is still visibly configured. But it doesn't work. It was setup just for the "current tab: [title](url)" command.

**Comment by kenny-evitt** [comment]
@chitsaou When I click an option in the popup menu nothing happens; the 'click' doesn't seem to register.

**Comment by chitsaou** [comment]
Thanks for checking. I might have idea about what's happening there. (should be related to this commit https://github.com/chitsaou/copy-as-markdown/commit/6f5ef29dbdf836b6f6c36bb978d97137f2ee0aca#diff-d6d76482dbe84bd526376a0136247722)

I checked it with Canary but didn't check with Stable, which I planned to check today 😢 

I'll try to fix it during my lunch break. I'm in Japan.

**Comment by kenny-evitt** [comment]
@chitsaou Thanks so much!

**Comment by chitsaou** [comment]
I just pushed the older version to Chrome Web Store. It's now 2.0.1 with version name 2.0.0rc3 (sounds strange but just a workaround, thanks to poor versioning support on Chrome Web Store)

It should be available in 1 hour. Let me know if you still have issue.

Thanks!

**Comment by kenny-evitt** [comment]
@chitsaou Thanks! Both the keyboard shortcut and the menu items now work.

Do you have a way to release candidate versions to selected users? If you do, I'd gladly help test new versions on Chrome.

**Comment by chitsaou** [comment]
@kenny-evitt Glad to hear that you would like to help :)

I am figuring out how to release to test accounts. The  setup looks complex though. If you're interested please send email to `ducksteven<at>gmail.com`. I'll add you to test accounts and see if it works.

Thanks!

**Comment by chitsaou** [comment]
Hi @kenny-evitt ,

Thank you for your help on testing the new version :)

Unfortunately I can't find a good way to release test version on Chrome Web Store to test accounts.

If you could help please download the test version here:

https://github.com/chitsaou/copy-as-markdown/releases/tag/v2.0.0rc4

Thanks!

**Comment by chitsaou** [comment]
Ok found a bug here #51 

Will fix it and release a new test version.

**Comment by chitsaou** [comment]
@kenny-evitt Hi, I believe I fixed the problem.

Please try v2.0.0rc5 here: https://github.com/chitsaou/copy-as-markdown/releases/tag/v2.0.0rc5

Thanks!

**Comment by chitsaou** [comment]
@kenny-evitt If you got any problem please let me know. I'll release it later this week if no blocker found :)

**Comment by kenny-evitt** [comment]
@chitsaou I just installed the newest RC version – no problems so far.

How do I select tabs for the "Selected tabs ..." commands?

**Comment by chitsaou** [comment]
Thanks. You can hold cmd or shift key, then click tab, to select multiple tabs

**Comment by kenny-evitt** [comment]
@chitsaou TIL!

**Comment by chitsaou** [comment]
Hi @kenny-evitt ,

Just want to let you now that a new version is released today. The version number should be 2.1.0.

If it was not updated automatically, please update from Window > Extensions > [v] Developer mode > Update extensions now. 

I'll close this issue for now. Let me know if you get the same issue for final release.

Cheers!
