### ISSUE TITLE
Convert web page to markdown

### ISSUE THREAD

**Issue by alexanderadam** [chitsaou/copy-as-markdown#54]
First of all: thank you for your work! 👍 
I found your extension because I was looking for a way to convert content from a web page to markdown.

Now I saw that this isn't fully possible yet but it would be really, really nice.
I'm basically looking for the functionality given in [http://heckyesmarkdown.com](http://heckyesmarkdown.com/).

Bonus: ideally with the possibility to select content that should be converted and converting to inline images.

Thank you in advance and I hope you have a nice day!

**Comment by chitsaou** [comment]
Thanks for your input. I am not favor of this feature because it's not the main idea of this extension (sorry for confusing name). Doing a full page conversion is not a daily high-frequent work IMO, and there should be another tool focusing on this specific purpose, such as, well, Heck Yes Markdown you mentioned.

Instead of full page conversion, I'd like to start from highlight-and-dump, as asked on other issues.

Hope you understand it and have a nice day!
