### ISSUE TITLE
Appears to be removed from Firefox addons

### ISSUE THREAD

**Issue by rcrx** [chitsaou/copy-as-markdown#69]
The Firefox extension appears to be absent from `addons.mozilla.org`.

**Comment by chitsaou** [comment]
Hi @rcrx, I am sorry for that. 

I received a notification from Mozilla Add-ons the other day about the removal. The reason is that this extension "contains obfuscated code or logic, which is not permitted by our policies". However the takedown notification didn't specify which functions has been deprecated.

I am afraid that it'll take me some time to figure out what should be fixed due to the ambiguity of the message.

**Comment by rcrx** [comment]
Thanks for the explanation, @chitsaou 

Looking forward to copy-as-markdown's return; it comes in quite handy.

**Comment by chitsaou** [comment]
Hi there,

It's now back to store. Sorry for the long wait. I have to rebuild the whole application to make it approvable on Firefox Add-ons. (See #71  for technical details)

Thanks, and have a good day!
