### ISSUE TITLE
strict_min_version (compatibility with Waterfox Classic)

### ISSUE THREAD

**Issue by grahamperrin** [chitsaou/copy-as-markdown#80]
Hi

2.3.0 https://web.archive.org/web/20181006155118/https://addons.cdn.mozilla.net/user-media/addons/505088/copy_as_markdown-2.3.0-an+fx.xpi?filehash=sha256%3A340ac9770a8a946117a353d49dc63bb4829e69f1d2ebd8fc8bafd8309eadd641 works with home-built [Waterfox Classic](https://www.waterfox.net/releases/) 56.2.14 (20191007063316) on FreeBSD-CURRENT: 

![image](https://user-images.githubusercontent.com/192271/67920812-861d1180-fb9d-11e9-902d-2d30166ee94a.png)

The context menu of 2.4.0 at AMO https://addons.mozilla.org/firefox/downloads/file/3423782/copy_as_markdown-2.4.0-fx.xpi does not: 

![image](https://user-images.githubusercontent.com/192271/67920896-cf6d6100-fb9d-11e9-9136-5fd2102db4ba.png)

Would you like to add a `strict_min_version` to the manifest for the next release? And (if possible) edit the compatibility info at AMO for all recent releases. 

Thanks

----

(I assume that a future release will not restore full compatibility with Waterfox Classic.)

**Comment by chitsaou** [comment]
Hi @grahamperrin, thank you for pointing out that I didn't set a correct minimum compatible version on Firefox Add-Ons. I've set it to 60+, as it's the first version that supports one of the technologies used in this extension. I'll also add `strict_min_version` in the manifest file later in an upcoming release.

That said, the previous version 2.3.0 was actually *taken down* by Firefox Add-ons for one reason: I shouldn't release an add-on that contains obfuscated code. I used to use Webpack to transpile source code into a single file, but the side effect is that the code becomes obfuscate, even if I didn't turn on minification / uglification. This is the reason I have to use ES modules, so that I don't have to release source code in obfuscated format.

Unfortunately it seems not possible to re-publish 2.3.0 due to the policy changes. I understand that it will be the last version that works on Waterfox Classic. For the meanwhile, please checkout the source code tag 2.3.0 and build the extension by yourself. I am sorry for the inconvenient.

**Comment by chitsaou** [comment]
Just added `strict_min_version` to `manifest.json`. Thanks for your suggestion! https://github.com/chitsaou/copy-as-markdown/commit/ca337a0d263ea7a7b3a1b7392689f73d5e7124be
